/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type MessageSaid = ContractEventLog<{
  _sender: string;
  _message: string;
  0: string;
  1: string;
}>;

export interface HelloWorld extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): HelloWorld;
  clone(): HelloWorld;
  methods: {
    say(_message: string): NonPayableTransactionObject<void>;
  };
  events: {
    MessageSaid(cb?: Callback<MessageSaid>): EventEmitter;
    MessageSaid(
      options?: EventOptions,
      cb?: Callback<MessageSaid>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "MessageSaid", cb: Callback<MessageSaid>): void;
  once(
    event: "MessageSaid",
    options: EventOptions,
    cb: Callback<MessageSaid>
  ): void;
}
